### ISSUE TITLE
Tests fail with pytest 4.2+

### ISSUE THREAD

**Issue by scarabeusiv** [pytest-dev/pytest-instafail#14]
Failed: nomatch: '*ERROR collecting test_collect_error.py*'
Full build log: [instafail.txt](https://github.com/pytest-dev/pytest-instafail/files/2865318/instafail.txt)

**Comment by blueyed** [comment]
It says the following in the log?!

> 54 passed, 9 skipped in 1.97 seconds

**Comment by blueyed** [comment]
But also:

> platform linux2 -- Python 2.7.15, pytest-3.10.1, py-1.7.0, pluggy-0.8.0 -- /usr/bin/python2

**Comment by blueyed** [comment]
But confirmed that there is an issue, fix coming.

**Comment by blueyed** [comment]
https://github.com/pytest-dev/pytest-instafail/pull/15

**Comment by scarabeusiv** [comment]
Ah, apologies, I posted the log with old pytest which i did for verification. But anyway your fix is correct and works for me too.

**Comment by scarabeusiv** [comment]
Full log showing it works with 4.2 now: [instafail.txt](https://github.com/pytest-dev/pytest-instafail/files/2868569/instafail.txt)
