### ISSUE TITLE
consider moving under pytest-dev

### ISSUE THREAD

**Issue by bubenkoff** [pytest-dev/pytest-instafail#7]
please consider moving this nice plugin under pytest-dev organization
http://pytest.org/latest/contributing.html

**Comment by jpvanhal** [comment]
I'm sorry for taking a long time to respond. 

That's a great idea! I'll move the plugin to pytest-dev organization, but it seems I need admin rights to pytest-dev organization first in order to do that.

**Comment by bubenkoff** [comment]
Can you please send an official email to pytest-dev@python.org as per [contributing guide] (http://pytest.org/latest/contributing.html#submit-a-plugin-co-develop-pytest)?
Practically, because of github limitations, you'll need to transfer repo to team admin (me, for example) and then i'll transfer to pytest-dev

**Comment by bubenkoff** [comment]
thanks a lot and welcome!
